blogs = [
    {
        "id": 1,
        "title": "Getting Started with FastAPI",
        "content": "FastAPI is a modern web framework for building APIs with Python.",
        "author": "Unais Shaikh",
        "published": True,
        "tags": ["fastapi", "python", "web"],
    },
    {
        "id": 2,
        "title": "Introduction to REST APIs",
        "content": "REST APIs allow communication between client and server.",
        "author": "Alice Johnson",
        "published": False,
        "tags": ["rest", "api", "http"],
    },
    {
        "id": 3,
        "title": "Deploying with Docker",
        "content": "Docker helps you containerize your applications.",
        "author": "Unais Shaikh",
        "published": True,
        "tags": ["docker", "devops"],
    },
    {
        "id": 4,
        "title": "Understanding Python Decorators",
        "content": "Decorators allow you to modify the behavior of functions.",
        "author": "Charlie Brown",
        "published": True,
        "tags": ["python", "advanced", "functions"],
    },
    {
        "id": 5,
        "title": "JavaScript Async/Await Explained",
        "content": "Async/await simplifies asynchronous JavaScript code.",
        "author": "Emily Watson",
        "published": False,
        "tags": ["javascript", "async", "web"],
    },
    {
        "id": 6,
        "title": "CSS Grid vs Flexbox",
        "content": "Learn the differences between CSS Grid and Flexbox.",
        "author": "Unais Shaikh",
        "published": True,
        "tags": ["css", "frontend", "layout"],
    },
    {
        "id": 7,
        "title": "Next.js vs React: What's the Difference?",
        "content": "Understand how Next.js extends React for fullstack development.",
        "author": "David Lee",
        "published": True,
        "tags": ["nextjs", "react", "web"],
    },
    {
        "id": 8,
        "title": "Intro to Git and GitHub",
        "content": "Learn how to use Git and GitHub for version control.",
        "author": "Alice Johnson",
        "published": True,
        "tags": ["git", "github", "version-control"],
    },
    {
        "id": 9,
        "title": "Python Type Hints for Beginners",
        "content": "Type hints make your Python code more readable and safer.",
        "author": "Unais Shaikh",
        "published": False,
        "tags": ["python", "typing", "beginner"],
    },
    {
        "id": 10,
        "title": "Understanding REST vs GraphQL",
        "content": "Compare REST and GraphQL for designing APIs.",
        "author": "Emily Watson",
        "published": True,
        "tags": ["api", "graphql", "rest"],
    },
]


# Dummy comments data
comments = [
    {"id": 1, "blog_id": 1, "author": "Bob", "comment": "Great explanation!"},
    {"id": 2, "blog_id": 1, "author": "Alice", "comment": "Helped me a lot, thanks."},
    {
        "id": 3,
        "blog_id": 2,
        "author": "Charlie",
        "comment": "Looking forward to more posts.",
    },
    {
        "id": 4,
        "blog_id": 3,
        "author": "David",
        "comment": "Can you add a Docker Compose part?",
    },
]
